/**
 * DeepResearch Citations - Auto-generated from deepResearch.md
 * 
 * This file contains the numbered citations extracted from the deepResearch.md Sources section.
 * Each citation includes the ID, title (domain), and URL.
 * 
 * Auto-generated by: scripts/extractCitations.js
 * DO NOT edit manually - regenerate by running: node scripts/extractCitations.js ./deepResearch.md ./deepResearchCitations.ts
 */

export interface Citation {
  id: number;
  title: string;
  url: string;
}

export const citations: Record<number, Citation> = {
  1: { id: 1, title: "arxiv.org", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGFeuZld44rKJ8kIag_qEqvLxl-166OmPJM3R8fo0P2JyOba8BB6BRg4HWSIUcVNKp4hyPCtAmI5q_6DX0x-n4ByWmeyno8PuQtQ8XOdKEKiGnaOrvJ18G1yA==" },
  2: { id: 2, title: "medium.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHBXnScP9Bvw8nUG6Jj-ctLgZKo0DkxoUtCmLwrpU8XVl0_h8b2WopfQdwXPPlT0Wo5FHoIBy0mExsp0tCNR9ukmoKwOeKIQRTfIUkb7e7B_2xgbSWHU8D8hZ4TgADcJLftUzspnOMcwRdExoUSe7SlEz6Mw3zazqNE9YzqaA_Ik3BdTK3z7xeqmAyihZXL1KbsPNcWWiaHKLcb06lmbRBqenO-rJCLTdG27hN6r6I=" },
  3: { id: 3, title: "theamericanjournals.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGNisfLIUm3AMzCtf0u9rEpZJ0Zm0q49SM0jYsm6lAYjmzJkbpjkf7Lq5FbLowEJqLJWvcuE-t3JqVq5SSxMcAfD1PZbKm2RoNApUFEv3N-6g0Ij3447apsJOUGvU746-VE4hvUMoDu8WGzgr71z1QDaKVd-kew5knfBjNvcLLfgiK3B7u2fxXMHQ==" },
  4: { id: 4, title: "carboncredits.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEtuYmP0GQWO4Hb2Hf3z8ejT6DAv4OeaiaQA1fNi87ddWsns6C1-rCu4vZUyYg_DHkC8ObU8woi-KgPfBJdqk1d8gwGazAE__TsT0Si2lW6NmqkfLodCVKEkXbTyRhsc4dsQoCf-6U7LXTDWiOw2Bwk6oyJf6DMyaLFo3cO-EqLWX4SuWnjg1lmwA==" },
  5: { id: 5, title: "google.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHlHEgjLU1qGIjYrCeg3wRriPOauSp7qxFh4LRCFu19H5EcpvOrnsKIShrVk4qEhEIb5846pnOH8ru0eojR9zZBELKEPKMqkcaHWsd1Cx42tntOlUnDrCwQn5OC0QXU-lkFqpjVfJbVBmcwzgNVdFz49qCNHj5dkuXcKst7p2r3w3Iv_4nrwn8G4G5IoTP5Cy18gzTYJO8EqMP0Hqrnu9I=" },
  6: { id: 6, title: "arxiv.org", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEnwMRyudHshooFN9yZAAAjf6n7FWo7UtrlpiCP_TbKvbuwLGhvn2vUUvFdF1B8iBxtcoxxP_LFVeDNq2-bsQ5LBRjY-CL4uWYePfBjFg5FNPBygyImkQ==" },
  7: { id: 7, title: "generative-ai-newsroom.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFPvgH97bGdxctb8heiIiiZtmDD-0saQ_ROhAYU0YKRMXgfrc5zkkb7umvquu9GqZh1djfHvPQhJOY4ELMsN8frh1E5ZIKenC90krzeOoTqMtYO8bXLG81NGvgTLMltGnCEVTqQCjhQ6cy8uPsg7GCJe-F5MFbLoL7l9FI5p4GlSXLZN9lv7JGccQobm9PV-pp5_Ch5k4Aj" },
  8: { id: 8, title: "avidclan.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEz6q1ELi4F1X2tRqKOqZGapPSYlU642llK_Owx30q1VrKW4dr_fwtUlIRS8CAOCXK1_ARhid6fBz_oFcxuYQjIBMN_bh3hQ326VARpgKF3eXhEiO1r3WehJCc3_LbnxQ_BZkSQUn__0PMpcox_omkn_6cRog==" },
  9: { id: 9, title: "boell.org", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQF0DzmLZhQELTP0Eiq3NNRWrDr_ldefK9I0awdT1JeVD8Tu0hYGQjqvBe589xrUpsbn3w44Mj6GA7MFGcwQgoOHvsgU-7ay7ueYNxf2_pHOVHL_hthQKah7pM6NoUxxRjd974zsdxCFA0BbRg==" },
  10: { id: 10, title: "lincolninst.edu", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGaPir8KM9q-8t8_iOTnbAqrxoqecYBeOxOLU7zfauionfatN8LKURYNTpcbsTxtXIpbbctbGzAh4dbnDKOxAXdXDZS6yfxQPU81D16llWZYU3jUJGy55sPoOMAbTAMXJP9KQ3yxaCnWtF_Zf5SoyYx_gRZOUZdsO96nYIzw4NMcrYYnuqJ_UERMImW-lmo_u1B7mtsl4lAJWMb6h0=" },
  11: { id: 11, title: "arxiv.org", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQH6biHZzDvV6xG7MAKLjG2v8GqetNztIgqIxFIvM7_s0t0teB2w0_--XbcY2TTfLhbBLXPjZbEkEpPEY76zGU0SKrsoHOKBl_Q6wvpJ0ycDIihL-5rH94Y9dg==" },
  12: { id: 12, title: "researchgate.net", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFUuhvtght_HxG3IHajg1Fv8gLOp7KoLuryK6ce_KVEcp_dPkOJZdZL9U_3rYml15pEHvoz-Yaklm4vvZ_QUgJ9AI6snSbizIxFkvZSTxKuP5vAEmTxZHCBKUlgxL0WMEsbdGmGQK0nzPvahJcsJiDH99liT8MQHE42QPTxS3rKALZrmBhOZEIoYYifpKKgJpyuoVX5MfZGJteQmtqaCIKRTxDPfM8Y7h4KySZ4PL7Rhw1mRS1OFNNM6tpwITxGuFc=" },
  13: { id: 13, title: "aienergycalculator.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHS3V_Xf_SKT-RKr9IZ51Su0d9tFfU72YLZIMD4jfTnEcZ51Qg5d2eNd1OFI6ymxBoCONoRAn9SFWcLGUVHvMGY--GCogqOcoaPkxCnfOEVGoJfXOPrmKeV6E8kCxCpnS3SsDnt_PqyUVXrTFEAVgFq17B1Tt1ZYhyONYsHh44galfrag_T" },
  14: { id: 14, title: "interactdc.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQH8qzXWMUC2_BdW8bYpRu3YwQLd61v-51dKrwI0kEtbfgy4P40UxDqCYIKt_7oBlyFMopfcDahiJFDVOswni-m8Kxpx5sz27vfYqvbSVoD7r0Iak58yxYpmI7jpE11eqsRIk7Yb_V1qWQmexAg6-UJCKdeIRCa5ebu7-5CLh0c6Sc99Mccm2TZsZ2X8QRU=" },
  15: { id: 15, title: "torresmarketinginc.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEW79yqs3z5hvAvNf2XiASiB3CXYD8xKU_IG521GRM8AjOV-Pt_9FKFv559XGkV8PC2l-P8JHU9xjmo7fc1VcnYk40YUYCR5_TMtDo-yafLPNFTkzjByH0PDeu89TgS0aKdiha-yhP02u4R6JlmWa_1MebWl_NJN7R4T_rXINoQew==" },
  16: { id: 16, title: "sustainability-directory.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQH6DpH2CCv1Q5wxuCAjI3RjMzLnabk3fFErYZ_It7rxPKDG0jHrhFDjYVATXMYVAfckfP3BDz24CUSeM67uJaot74sahUq-ObU2nVBhOcHa3f1BmkIyldF64urKBoI8BhFgI6dMj6_ZwTUQoTHjjeyFLEVmmC3WQyEJ1rzVQB3RnuiS_gZpzVRJqndAiOOb" },
  17: { id: 17, title: "researchgate.net", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQH65XMo4JC3JqPYIzGq4_wSxiTLRE42TqPKk2rviojAtgd1w4UWCHPbJPGU2oE2AUubq2w9ExdRJBtCs3f_GD8usaT2Uq6cSQK2QCrAlG0jYaTZscSQsjjecRJXumLo4mmZ3EiJ7kW4ThuOpwJULXIKfzSjo5plJ7dVMhSlJJqBx7g2MbePsYHOixVEBPdh544tcgZu_-4ZARQ0NdmJPP-9tmswfyJb9Qiop0WeEVhzpWxU-J0qMpphZ0NyEYZTLvvYFsA4DE5EduCo--Biq7T86f9xl6gVoScse9NODxeGK4A9GhKTX35cQMIigAD9T6jjgo8N-g==" },
  18: { id: 18, title: "marmelab.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHip8TKrlq--WqAyLniC-yF0z5TBPh_w9peBorACCQ5H3XPn6viTMjUSHrfIGhu-tSR-ZvZaDDwq-NzidqWK5lfOqQDxNsAsehji-KvbITjtoajI8Z6NlNB_pnM20ZkagTIThXBOyWjifAdbS7szKmz21_i" },
  19: { id: 19, title: "deepmind.google", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQG4GqBECqZaTOMnQpP_NGQ9WjVSQzqvaDmwuAEWahvPa-HrW8ZD_VqyzmMTYdeQPyKuS_9A4cRoJjReRAKLq1_1-KeM1d-KNJxc2YS_zDHjrdTEAhMWkNqrvaYITWDFjoN2e4w2UsidlguHhHprchHQ5-kKCY2N1sd1aEfeR9hDRWaziY5UQLl3X5DDA-bmZ7RxlH-BnzjknlkfJJmVJg==" },
  20: { id: 20, title: "arxiv.org", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGv4V1PzaSk3-sCLxgH4tmgzvDgl8Z1ePszA6AaOIH24DC2y23hrmccpzEKJgTMplj-ngluRZYpResiB3-0EmLoxa8_jduNARdMnAgZ5uwW_jiV32kJf8uW5A==" },
  21: { id: 21, title: "nvidia.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGWllWHP_RsX9Zb7iXxV8hWbIH2gd5YULOGR8ITF6Szx-NgecqjDW8dqmhZR8_aPYXEU3Dx7WMZV8DHMY0XLlBxzxcxG3-6UOKBk0pkFmS6CzXw8ZgebPqavS7BllAa7iJJRcDxQtZ6wpCUDha2xQ-Y8z3-2WTT5-txm6EV47ak6-AVqohcdTy2oO_2iShVYOm_JCSLK2crr9fOe-r6wLZv-ZHfaFgDhv0LiyUwaQ==" },
  22: { id: 22, title: "arxiv.org", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGov4Zulk157k8U3NyjoU1DFbgB1O1aNf46OsWGe7FYlziLAdOt9OTNz_HWDeqnZe-nLQ9je2KkBqp21-DwggvCGPC9WVRYD58-Jiuw63Bt6f7kDjA-kCN-pQ==" },
  23: { id: 23, title: "ijetcsit.org", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHDwVknOasBZ_q80krYp6k_CGE-tdmhGoeLfXIlU5FpND9-sAhVAifD1pp6MswnvKxSn02EMKjK0DZMxjWHvOjBsYcVuRqOcGwFkpZQptoB5cQkXvOKXXlLkvR_QzHRDiPE1KQEV3gLZpNsbLl3wt37toG2Iw==" },
  24: { id: 24, title: "eai.eu", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHFbmMMi2J4F27ZBKGedobyP0t7KIPSMWr9K6DLE9PT39jMhtaiw5EIBFWkxtB6CQmkeLt7hqFhS_d8Z7-rm5Tq7h3vyYWEiPiV9k-QiWWFJoN5hxBNdG3Rrzj56gdARyqNFhkzCQ==" },
  25: { id: 25, title: "ieee.org", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGY1hxqvrkWBy6xvB_-8gXNshFmuSMQ1f7QpC2mMayKzwv_DJWv4Jvb4E2fO62LOvR9kwWZVKqTDCIo4XBY14MRZea06Xj7zj5BKFwszYLxDg4Ku84UBYoIOhRN7N-mWmBf7uJ6" },
  26: { id: 26, title: "preprints.org", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFQrn5BuGvZNrgtD9Ipy6-Icza9CeVq83E5qftlta-EYkHOhZxwFm_4v3EaHkV_Sf9qBwWU6Vu4DKSAlSLXwKLkY-IHiAilaTVHJfU7XYwnmoG6vAK3n3Iyv_du6D1HxogULlv8ezU=" },
  27: { id: 27, title: "wjarr.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFPDkep9-7cf3HoIHIECmZYcN_aaMyCQka3hkYCrIp5LATE4PJH6QZalvUUSn_-Spuk9eSx48IJkgZVyCARsW_MJoYx7gzt-yM0a8sUAI1qIgZlgudPfD6p86Tj9RKYI2jYge1HCFWVQD1zkmuvF0Q=" },
  28: { id: 28, title: "horizonepublishing.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQH7Rxtt4tinFHeJQoG-mgaULsPtAWQnhbm6RjmMJ6Z8uC_hJ8hLAHAl1dmL-UR28_MtUOu_YsniJW-l_F0dG7YMQbT8JkM5Xkn5zTotFiJWfjIec9gszHJnZmIKe5Qk1E9nELzSycHliNsEuvbWir94zi0gMw==" },
  29: { id: 29, title: "researchgate.net", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFLOUGxLrQFpGlCDb-2o6CvBx8sfqan-GOsMA39ac2FTDJKiLWPMd9I537mse_c4e8-5-0UBdGM7qldu7D2QoyLhtWTnOQOkF3G9YpAS7QiLjr1Kjw603EsZsnZDjKr4wHhlHgJJwTolFzGShh1bZ9mJaELOWvWPGyG7x6Bit-2CD3rHOSjHmHQo6wNCjJ7Brclbl-S2Wx7EzTNLMOMAZZHdmExkJt4AaOpnjlnsFjm3VK8t840wRq3Ole_mL5hv5rJuk-xflwdc9dAyKkntSMnqSTRQEbC6iFNJ9X5esxfSB0vjt-gHqDbDISqKIGQxaWVSWuhPZS-BAHQ" },
  30: { id: 30, title: "medium.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQF5VS0jIMNlSWAJP5yYLxNm4mGcvrxf-m6QLevqSyYWYpgWQ50UEVn8P2QYAUBCb35lUMmX8SD7Zy_rQGpLbSIzPKYwflDHzoMnbG3tJdkuBNzSQmZCKw9BAUuNfA-Dg5ipB_fV8V_WnN573R27vzZr" },
  31: { id: 31, title: "medium.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGsLjFATiUWG4cMB2juJKRMLZ0gHZdvDg002n7Qd0yq30u-qDv6Bmm2XQEcqu8BW7PFzr5b7AFPr8h7CJ-uFCrxyTr4yrj3qxI8WPefFvqWBvb0qzWyNFO1tujdq1jUjsHGZemmY6SJbU5ynsENZw6CUOg70SeUxhttcs9nqNmW3LgQoxOdcuD1y3cu48XBAyK0-2msd53RPG3RpKaYJds9WBjn7sPXVPC8uz2Z97RMb5w=" },
  32: { id: 32, title: "sustainability-directory.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQH3VbvJhY2_U5_LdniMvABf1xFaPfc_zjBa8PVJLONq3LF-xdzNG2zg6kh-iYjL4CIHibPDkKG2Ysa__TQ04p5l9vj13KFwlen9GZ7zPFRT4iCbIGDH77sk9hxvuP3JMPQtuz-FAuUpSs56aGC_6oyeXIgxl4iEXepQHC0TmUIm3icB0ZZegj_lHN9bP2dHnEOsF2t2HWBGKjePDeZuyLzKTyxMEVtIzQQJXNmqJdS-xDdQHwPxSHwDX9YFhA==" },
  33: { id: 33, title: "ijsret.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGVYoZZvKs8hQP-jJoKk2pPAC3keb2CMyMLLzmCpzV_vDhLNOrx7pMONPJtgPjsWGKMvo2QDa_CsuK2mS2EFSRjSAdsDvCL0L1IJbo_hxOQIWFTOeZKzMbbyaNMcLMfOF_fac_l6TqA7m_A0B9pMuzyIgd8MSi3" },
  34: { id: 34, title: "aicerts.ai", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFSiDu1nOee-d1ZEtsYB_GqLpJe1mdcfzHALV41L65_GEbCxw4mR-7Co9Wsx8SAlFZTjpUOKKdlkVJccC2Yl811jie4Bv7Of1Wxq9k8Zde8OuYDNap4RH6PAuxfJYBSvIfizQxOosffhOXXSM01wLEkE_CrvyiOhYf2Vl6D1aueo7L4sw8XWG-u5m929DFr" },
  35: { id: 35, title: "tdk.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHzwPkle3pUIZ7tTTALFzVWVE7_DApRoHSMoLQPBnWiWI8WCgRC9_r4v7-nMlbZTWlbUZ31kMad5g8WgEnvO4KU9htaEWtRQTf-l8jeOaT48osKgiTzBmYNuzPwqlK-TG7Xrl63jWZvJgdCyQZHu08mCH9x82zT1ozFcwwi-1m7Pks=" },
  36: { id: 36, title: "medium.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGY_O9R78RsqxueRhiRUxbNeP9512fKteYhgREnDsDfM4Cyv2MW7yx80A6ZULAmzsJmeb08C9Yp60GqXjzEXps8ZuY9AeAvj5FBzSrwXnnAdcbvIrMfIL-JDv0bnKtWU-6tiiI3y1xF5InxUC1MLP4gV_UX0-mZMxmuyhYR72nrNSD0uRK8LE_ZbowRg_Ss3uJkb6pjFJIWDJhSQL8aYrROceeH9wC4JCNPX6O_0Yw=" },
  37: { id: 37, title: "humanunsupervised.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGHy3uWRgyg43QiLMHMXbSY1SwquIGTFWsMhmON0WiuL6zx_1SGVIVcFveVH1YBPYgu5QSkajjHQVq4VDjTHqrL_8lhKe6UlPYBgcenX4dsJhdf6CV2ORGEWmhmixrX3khi4_8Qx-wMYwPTqDGFogUN6s2UZeJp" },
  38: { id: 38, title: "elprocus.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGlkc99v9dPkn42f1boL_veLk1KI9LJhrKd3Y39QwzU4vVwzZBVZoK8flD7EwV-G7SlLt0eAVMb4i6XlntKWjR14n1O8PiaJrRsI9zJ9jdyTb77Ic_BhR6Rzc-JWvtAigTVIo78jVUw2CCN2E-vaw==" },
  39: { id: 39, title: "nae.edu", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEg1Blv70bH8u6D7SWQ6lQz858uJY5f-mDuSK0__oesUPlMSFU7t6nUTsbhpch7PO9Bs6oHq9_KUgXKzKnCI2LdULVWQkGYC318zyvJ2Mkp6rmwN1CiGg92RTi6RkIN1z57IqmduVj4yhT0wezeoNDQZRdI7T8WOqlb25CVNwRI5_8FGygGRhNS7Y-79nI=" },
  40: { id: 40, title: "smartclasses.co", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGGggLixwZVmkA-oTnk5Tvh9DnkXEJzvOVQqNVitk9tch0OMqN0Vb9pA2bJsULMjH3ex0rrmZYi_Ku6byYqeBTbOtYUFag1hJ0qIaXnyQaEh0P5oxIeLUQIs8K8vg1umYgne7FONjXaKUobDqeQ_8jB3daxeEVtGkKRR5f8G7s8QWWwgAmZJyDvOBJ9oi41lKZePv7jLQJrVQZIfg==" },
  41: { id: 41, title: "columbia.edu", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFjg6W25ms-kq04agf4j4tirg1ZdOa2SI4qvmIgjAyk6fD36f_i7zuTVjP8UWmgKzj_bQcymXXc4N-QH2PDpZ7FQx-8XGsb8Ru1iKSsXGlYHucX6Ob3hNs7ObYH-qLVvw-mfGRn3XDFODf9b9fcgIOpGmmKK9uOmQq7DMQ9smyIB63IpFieQkeVEVMQ0TL7IA7Cw0jn" },
  42: { id: 42, title: "forumforthefuture.org", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEC5WJXjzOHyVKUDsz-1df25cpFdDIKj_CcK9iZdDQg0GJ33bCuaaYnKCbQ6Bw0d-7dxMTctlW2gRYThjq7egodQ3ap8_U4YGRpW2nEidN5ADwoxUAKwk6woR3NRuL6d5i3FQfsP4TzaxvW8Q742FUcuiJNwmJaT5EzYz3xG2u7xpOCFegfu0h3oFTJYTuzyTX90Q==" },
  43: { id: 43, title: "aiinthechain.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHKS2u_OXoidYTrbEAD2vr6vLgppjs4KwVTsqmGBQvA7wVLTfCpjrpVyTuodOy81NWekrX_3DizFQtEoLHmc1P10SECX2ZeiY0okSl8auOKAXHpEqMMeBLD3glSV3jqCjYQ_BBl2zyWC1h5DMlh0DASOJwEcm1ed3kZd4NtBxLH8IIHrdOXABbkLYIwGKxo3CwP" },
  44: { id: 44, title: "arxiv.org", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQG53H8s9Vts3XN-TPtwhKyaC5yTdmsbG8ewRrDT3lpTKFss6MahNg0iC3ksV3OzTkSagWtSmF75JabdXfCdigrReeDEqeTuMfrOhBfxY-lHYOgBzMPyH1dW2Q==" },
  45: { id: 45, title: "climateainordics.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQE8sKC5HNHECAjQQqt0jlwhRQNYmdIpACd6DJ3yfzAe41W6SCpR0AKk7vV1MbslTO9kmrjKOdJwPjAeWXL68oIfZH93fRxpHDuA59yeW9ThgNNoSQMKLOsGhbnnzv_vdhX78IIyiH023LftDbnh-K2y0LRT-aj8WU2mGeCywbIYIW2Q_FjDg72_rjD49ldCnMWqxaX7t5i-lT5XzjkXVlWDck5h" },
  46: { id: 46, title: "visionrobotics.eu", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQG7BqMTUmwFJB93gko8pthJzU89pFroGta7qQ5oO-kjN9OAMPShOhrBbnGyy2uGKmjs_RnI2ILTdEHaEm8up4LHdDLrcG8X1amG4oGTJuehXjaJuc-G0NkH-L21YjCH3bJHcPlOnCx4ZaYFH2evne9ZvR1q2VmOja-BhF-uEVNSMA85bSs7kq0IRik=" },
  47: { id: 47, title: "ultralytics.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFj6PdTgdFzUTHHpFj2_u_Kt9B42xr-nTK0a10yAmQm2rKWV-B5k5lu-0JR1UpbZFWN-pWcXlQPqoSok88ehjsED07RurI0xLl-Ks4C1tCBBdt6GXdvnSeaet5AgqJmMHAY0SzqX6bg1qucDu5xgX5uETJBo2W1tzSwSKKsCp0xXPNJU872a0IZ_0xf8ZHKX5U=" },
  48: { id: 48, title: "greensoftware.foundation", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEQn7PtU2LYNmqLOEHlA-QsxN08WBvI5mL2fMSEKuaBO1v51EoG8p4e_cPusNffD_llk_NjERixzTt36xxiCUiRxUccA29ywMcoOoIoWWT9VIP_fOmU_wye-Z_nTpagiZ5VDPvve5DtqnA7zqZJ2LaUF88G2nlZNvlecyP-76fpi7cQ9XBX7fwyKBD3EmVr2K6jYD4=" },
  49: { id: 49, title: "rgpd.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEg5izh7Fim0F_MY5wHLJZD73GPoAVLXYw3ym6S22hChdV19OkJhoAO9KcrL8L5mUG-c6z-23ua6QyPCkiOtMYgDXHPL6l14PyHtIBotAxwLGJcn6pqt15SzUM5FIbU8wE7VkIl4uKD5SReyb3AqE8faof6saahC3DA1-4rhNA_5xw-vhBzYBqWeCWyU5lBXY2VhpZjM_0opjjDeKVO7pdwXKVmeMA4sGUNKehBds8=" },
  50: { id: 50, title: "whitecase.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHfHFX7j-WVcC-GzEEuRxHl4eqD9X-XZ7ZY9mDU6yvVOKUn_SbGPKa8AcPZ5JBIPXuSF9FrLD612n_-o0aoeH2xa_wMNbD3fnaV7m-ZTszwaaELT93JmUL4knW781zhWRdobVA-hgvy5_YRyLNEnlsnq2iZhN54_yXXIQXDLBjpqNSfA9-P2w9o-8jbHQ==" },
  51: { id: 51, title: "artificialintelligenceact.eu", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGXDSPZhmGkKt-IoA_F3fRMEGh7sb9Ccvz_j_ZJSGx2XOlyas_s8AU6fK3Zz9IhaxgaN1pLQlkWH_M8iPdUlZTN2u3GR6kECD-l-d0tRuybJKSBE0aSxC_a4x220FcvvU8N8KdPI1zUViTE0qfs2f55wtdXYA==" },
  52: { id: 52, title: "boell.org", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFY9ARaYJE5g2msWf1QOmXXevPARrionmWwiOoHgUKqOZ2GsnBszCVMYHRv79lOoCFprfD5HTiRYnA2gREyhMSNPfwOaGZaR1ii212U32i6sgZstdGPmTinh08rr8IrWAUJMP7--YMsIj2MvWbpCi3oIK5YlNM=" },
  53: { id: 53, title: "nemko.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQE_llMleqRpQv5Z0cUR08FdTUDG6sp9eEVIKFVWKMVE6kZUNPxUHvQ_otTWHomSHrMpqvmj08oovWblkRIBIUVRRPHcSCrdAtuhUiGkqDlQsRcWGfes8NpXZJsQ6x21T4VEsf4zZBYY" },
  54: { id: 54, title: "jtc1info.org", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQG4qejmM0Nq-s8KkdxV3X-DypE0RmVfgWxri6obizsqhX6nu6p_KB3eRzPD9fBEmDYn2fIv_ng_TcAk4OlRThoezJuTTaidE3sdta2Fp1IES0v-i0ta_8sT6IsAaRwyNs90x9038xVZ0NONMtcmCEmOyHbz3HfbIyA5nvjiXRhcB9bRqDAi4D_K0lQ=" },
  55: { id: 55, title: "youtube.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEjmKbBfoDZLHhHy-GTwBCd57M-QM315cfC7WTtvRsMLMvz6d6UN3b-drfjuG_XGUySmxqJYcY6bAH34npMccdDQyL0K0say5le5g2EQaYKY31j53hGVESockm6K_V7Cmqt" },
  56: { id: 56, title: "dev.to", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQH22PZzwcdojW9Sf6aLWanP61z4BPVeyVsy5AcRbBu93_uMfQpiNR7wHPIMieplizmEQZZSXoujGTdsr-2x4XWqU_dGDMtuhq1_-ThNqs5PrgDv755TqlTbAguDrZOfewbP-TBAkHDoFkubMqy05knKhndZYzX5P5SzdXHVi4xyKtyWo1kAXbbxDIs02fIo5jYfcVCJH2X9U-_jZhGukDQI8muNayxy" },
  57: { id: 57, title: "deeprogram.org", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGDIiy70FjrbILQzaH-b7-87Sc9z46BxjFYSo-pxcWMLBXDWyAmY3gwS0UV6L5xexwI3LZd0nItRDNklWNCVjES6cYSdga67v-gmHy3FbXuBPfhrEsbHtcWcpAxE_Z89_U11ngwOYmoqtp_LvucBRJZ8b1Ak6C57pir6_F-y3VowVhMnmHUFxZGq7vK8acG6TGtUN-S0VO_4fQPClY8xIpBqvdhK0KxARz7fKxzLlyHfnPn85jAo4RVAPJYYd_X" },
};

/**
 * Get citation URLs by ID
 * @param ids - Array of citation ID numbers
 * @returns Array of Citation objects
 */
export function getCitations(ids: number[]): Citation[] {
  return ids
    .map((id) => citations[id])
    .filter((citation) => citation !== undefined);
}

/**
 * Get citation URLs by ID (for backwards compatibility)
 * @param ids - Array of citation ID numbers
 * @returns Array of URLs
 */
export function getCitationUrls(ids: number[]): string[] {
  return getCitations(ids).map((c) => c.url);
}

/**
 * Get a single citation by ID
 * @param id - Citation ID number
 * @returns Citation object or undefined
 */
export function getCitation(id: number): Citation | undefined {
  return citations[id];
}
