/**
 * DeepResearch Citations - Auto-generated from deepResearch.md
 * 
 * This file contains the numbered citations extracted from the deepResearch.md Sources section.
 * Each citation includes the ID, title (domain), and URL.
 * 
 * Auto-generated by: scripts/extractCitations.js
 * DO NOT edit manually - regenerate by running: node scripts/extractCitations.js ./deepResearch.md ./deepResearchCitations.ts
 */

export interface Citation {
  id: number;
  title: string;
  url: string;
}

export const citations: Record<number, Citation> = {
  1: { id: 1, title: "qodequay.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQG-u6eVzShUM2MnedCiWxlDoWfXq8nhGttBZGeJ0VpvNGmwGEe2FDuezl2hhZbl-NgvasG28AfpaAj0x65PNCN1Uxel7RMf0HIVmhO9I0JQV92Fl6e4UFgdO6rURTlg40P76u3EfSzNFCtuJqbk77Adx5_yNhfUQ3mQcw==" },
  2: { id: 2, title: "consumerresearcher.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGItf_zs8SNPnOdWBvkH1dLA6XMV41TpK783sYA06pfFSKlCdIbIEAGvVJVemGVxPAi-Bf-PSgyLVTjdIDF_s2b1GsBTMXETQt5zGj0Gv93GVDbFGJDfDZpWU_nnQ3fO-xt4GNq3PeNDqs19AeKeBBXxStUcE-ez-e7u5qZy8zGn0V-goeVlvcza1wfo2ZK_yY=" },
  3: { id: 3, title: "tracxn.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGl9PUxCh_4_a0jQUstNTqGYZTTUq6TnCACWBEVffM_euV4beTkgjAWTY4m5UfeBEjwgXnuK63_asl0AtKO2ir8VEshefb0yni5qKC3PIWB8NzzEmqCMQ0f9N8nXGf-F71pO0oMEEil3yG9AjxU0NV6RJitAMkKd92EOzsKuOEy0S37xjDvb90=" },
  4: { id: 4, title: "topaiproduct.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQELtAPpJzU6CXS9cGglq0RjjOSHp9mhV0cbzsNPhNF7la385XXHXEp79y9Oc-Lhdy2fjn-nMdFLbtVos_UHpTuQMoMyH4EHTbLpGDTiO4paWz3CP66DaLEOxKCt5Nu-vpv_hQ_zq51Mz0fbSMuHGc1MmTer_WWs8ZVUABGBKAYqzF-3XYRO32MNWi4VxqmP" },
  5: { id: 5, title: "lucid.now", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHK7BlLu_H3pqjKOdzRsnbA8a__BvquF6407MGJWT78Io1Kk7gxSKdi1vz4CSzPiWf5WulryHkya6R3dMQQ6VC_F7sJCCwxDBipLFftjpYJQKVRGMDqOhwJgNl1kSqNdhvsv7qL6AxhNIKLifjz8R_p" },
  6: { id: 6, title: "gwi.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHLIrpEbiSPRLc2k4oAy3kvro-49u59iXU4knR4lDl0hzXa2yz2IUaEG2R72vjxbWcFI6_5pFc62kftDfF1Liq39ffV7lOsHm4cqNUo2fJR3MuaB738EGmddGnIqcYsT3tqAcgaL2Zu" },
  7: { id: 7, title: "adamfard.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQG2YWrx10VV5NZ86ytlxJXGSYzlywk3c-9RDXYiepG07JYTPKe8UXgktAHHfEHVU1L90wikbPseVzOpDsNhpjadXAJ2dvYhfrSWTqMjHH65eT1yY8n5uYKpj-VD_LkN-fs6KEjl9usS6YQ7cPiI" },
  8: { id: 8, title: "autobound.ai", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHkKSMENIiqF_R5qu4a_ROvjamoTqRIglOFsrPcimK0BM2luviCkwavPgBIU6Jr6Sv7Y40Jf9o_rld7gQstAwfdlCuf2HEGigzz7VfGkHafwGHIIII1XEUa_vo3H7ruC-DB3zj-pcoTD9MgA_ZVoz_M6MCXuIgsFQFm4G3CtjzWBw==" },
  9: { id: 9, title: "competitors.app", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEkk29a_nE1lBbTnk_eyhGCiMAYDnmXWWDBt6nScd4Sf3z1BRgQaO6ZpI6VHRuKSBjApogRHRuKoJGCC6wU_rtxCkI3m76t7TFdH_YtlhnkjnKC5ohZp7tsIamHiGin9xLe8uur5mnc-_Efl4BPYgHoX4FYuloucBp_GMEYAJ6Lsb1QcSxyZdCVzsqjEg==" },
  10: { id: 10, title: "crayon.co", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQH9-phMbRC5DAWF4ZPqIuLCu-czmq3LhpLkNKF7pFpNhTAJ8yu2b2ikN2YAH3K48nGiAGrEX9oOP3DX5O9df0pq_nfpKQJ0CtK0-OG0YJ57_z3Kb-YLo_TgNqs=" },
  11: { id: 11, title: "diabatix.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHQhOOwafwIWqZf4Ou9UOOrta1LxIR7XIxflf9iBLcnsfPZEYPOFULigTZdIIMc90_oAwvnLSAp5pLofrxODP8hyQFPmPY4_fFWK_wJhU9zF5pg5mZJronXzrtySVkMpUzL6w2i0msrhJDR_XgOMKI=" },
  12: { id: 12, title: "diabatix.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEix-8vru-lCY0myfg-PnjpMpex8KGqXDY_6nFBU2b2RrDZ6NuiZT3-CvSFp4eDzdjPBiV9AXg7ss-FXrKP4uz3qhHWjGy8BQR8NKXMOojuFePCR73rS6YojEwm-X0q7Fzq-pVSyVFqKKhxpFThqGSmZerXvXssOGZb-YJlNr6X3JC2cE7G4e0aKNH3rVVdg8heYJAzxhshJIbVvktOg8LN_PxY1TA_nietrgE=" },
  13: { id: 13, title: "infinitform.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFbZ1t5Gp3ehAl8HGGZ4RMR8JYfXTSOOCPaL_jGASweKtwIgjhlgaEkNmRN4LCtOwaynyuwG2JIWTYxi58GesBbutPDfbFky6wPo7mzH0fbMvO9mw7nTlkSTvnCyULwuDniJvd_0LZ0N85YAaWm1n2phw6pv3DKy8Cz8Q==" },
  14: { id: 14, title: "aimagazine.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGaF0db1DXPrbAKvDQBGecQr4BKHAr990gM7PiqKrObH2rupZ1ScAeUPJ8_dTB-oZ01Erz2Gst5RdLS7V1Q4olzL8HWzAc8ZgkbSeTNs-LFRRnN54gf8meIVaMeH55mTk_E7w==" },
  15: { id: 15, title: "mathworks.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQF8juAmOXH7BiiojHLb6UoJlcHbsoUJUhorZ9qIV7506qOxqW9mItlHJiFMu_kmqZw5L4s53NfzK_4trwX1UiXRbun9vfstfVs0YLu5FmIjXK7gMvVDAfBDOyhvbs4rSCKNGBdfwWWOUZ9h4hYFlXypPkRx1yCXnQSqOFHvK7F6" },
  16: { id: 16, title: "wikipedia.org", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHdYIbocZjqv4PXAlKfAzRSfs0auv_cskjoDFSgG-qMlmPhdyXWQJjdYpKhBbXaPt9sG4Uy5gErE7xkki3_nCq7wZsLJ9Oy9CjD6gPj5VzAgz_1mWcbE74P986qVGTDF_Q4ZVOces-kVx8lNSvAmQKCYz6Y6Q==" },
  17: { id: 17, title: "caeassistant.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEUyHA94DPdNBgt_9a8uaKRvTBXGC6n5q8WbVZH3-ZiJOp_n7eS04j4dCUKpoRwi2HmkB39e2YGibQPykW-KZMHEa-A648tazrwhs-2464vPGKRuHsWbGI_T4rKchJ9DhdXzN5AXWAUGGRFTkr6_OI_6URTcGbvcgKk_Fg=" },
  18: { id: 18, title: "nvidia.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGPlNGG-nTYl8nihjF3oUpHmAY48ixmXhsVXHX_09dm-n-lpptcedgnlmelmK7hnNXiir8y4jCUWVfCEi4vvV4UJsTkzGMXk0Pw3gtWy_HhvW8xIJPEQglTFRVSy5ycIVwkoPTxBFBk_CjaUYfaq8ezdHtj5XSoS2A7ixKpXeXJlHLA6Ag6fXb_KzOXGckXDGYogET8wg1W087p441osd8DGMaOLo9Nd0j04xM=" },
  19: { id: 19, title: "k2view.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGXEFzuCC6GE7ihf8qKHIbkG9dOryA7Ka1rTqN5sa0Cs9JnSeWv02at68hOdl-IBEteIVCIHynEPJGnTJM8BymSUya-gJhPvxM6YnMsLo18xNJtKHJXQGJbQQe-4D8h6he6ypMXyDWRpCCEjVgtXq4=" },
  20: { id: 20, title: "ibm.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEiqXl6Fo-vjOyLyJoEf1AHkGqArJq8g_7K1m_HVeyl-ynyPH-ytQxp90Zt5n2iEKfi1s1H7GyaGEXIcnJhGV3uvS80oXCxX2UGZpyq05iw8N676-YYfXUmMI9ok8Y_23ybWl3SOo8fnZjhKcnwE841sTw=" },
  21: { id: 21, title: "mostly.ai", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGztduVw_0o7g_1Ds32p7p7DIp8iB9FJfwEqIf2FI8rkhGsVFwMw-2LZg1_8V2MkaVcoAlhoCcSojTaSEuA9Sd-7F1iDNQSW1BuSSrWtxwSIuGzJkfANDsh2ZhtHwI=" },
  22: { id: 22, title: "mdpi.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQF7coqPiD-sz_BNLvfv2gNLWWRnVgYoP7Q7An7Kkj-hT7HtGfpmwuVTwOH9Rerxbjgz9kbEOBQ35vuqGJJY4BCT4GvUUVQJOY9U7u2JcZN2ln5vU2llMncRZbX2mGo=" },
  23: { id: 23, title: "wevolver.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGUCjw4SlLJp8zut_gQ1WD1JvIblEBwYlQj8otJkwhsjPmI29uDpXI4SA94ZZ_5FNvguzFtp4qCksDv4-YYu6X1S6YOpk6O9ht9P-3xguigLkEH9YF26wiOKoSYvBC4BBb1jfT_A8E-fDCON9sICpNLCP4p8aBue0SDxKQs-JiT5Qq-xlyvdkUqExqaeFfyBoJGrlFgLA4QSnp5ra5ZrQ==" },
  24: { id: 24, title: "neuralconcept.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFp8ibMYWl9jSwR1nbCLJwYD4Q5HNU9G1Kb-QnT_FJWhv2wN-J2xonJJxaOMqwdfSedxGwCV4JXMvdKT35N-KgIWTply8bWdz4M8Q2DF8bchAla3GT3mKq7imMaPErYynELYEeicrz3hhn3-D_MlhcGr7J1bZosDj1y9vG0urmaNPmkNZv_cw==" },
  25: { id: 25, title: "digitaltwinconsortium.org", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFBprFMcwZcZTKzaBpa7wmkd-9NV2NKS5lwTx21vszKcgzneLmXfxPMImQepcBb0cs15YJq8PoU3OVCti9ODISL-yi3Ispk9FFHksNuXx15vmd92sdoT1GB1BcBZ-_sZXIqkA-Y7nPZCLIXiwrRAB_eerS8TY3gOoxNk8u5Y2493FPH8pB39cDbrhno_K5MxED82kn56vyrO1f6lL4FpZsSB4uJaMX6vQbyoUaP0lCunegjIGjojzT9vb5cTNsZnm2ig2golTYGTrT57w==" },
  26: { id: 26, title: "cam.ac.uk", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGGSX6atiFZ9LJ2yOq5tQI4Jwy3yUGhZQSwfAlJMfu5DBFi4XFhcHuzRxJMOAwLP6YEmd3btsHN766n7EQmEDCU0Q7NJfXIU0GngOhqoMl-D9_o8jlHPZD5Z_zmoyEF8UB6oS9znQz7dO5abzdDtPkbV2aNJpc=" },
  27: { id: 27, title: "computer.org", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHelVtN7jx4W9JYRgMDrHJx4eG_CKesaOGpgwtUX-z-tgRro75I3nxYX1vQYdq6J6iGE47vuY5xFBbExdxwp0FxJ5gHJT7fF0DgCXMtTAwnTB4PARRvcbgv_u4kdp1Ul5-nKXeK38hBf_ZFKHWGWH8Z4XaVLCKxt0WbNuU=" },
  28: { id: 28, title: "colabsoftware.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHoRlo27rGdTkTQwgKSQF6X1iCafgFNNzU4yOiDCgrZ7XkmwWpd2M9_S5V6brcpRwgxeP81rxr5DYhNvMv8iG9XX0pE93u0NvEgBVheKtK_UM173NyFG21rq8VuyyZUg3-FWIEjuvv4PKIPuONcHk2-H-p-yqYP2qm4bsn4zKT03cZCAIzdrrSmar_3QNIHrA==" },
  29: { id: 29, title: "develop3d.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFu5AfUoe3rktxT__zIZdwiAPrtWhW1g-3D2W3v4GhXff_I5-1Aw40LKnhAUs7zt4zlNuao6JLG3LyQjkkWfNEhpxXpuA-4OlM8r2hrFaAjnanINPAYNd9KswF0omJhoVJSFdFxsA2Pc9k_MfrgIDfAEsxORH6uABawHP8_hEMknaY6qy6ArVI=" },
  30: { id: 30, title: "colabsoftware.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFA_9kgavZ0RiiXQpgOCkWFvbrSp8cY8Li6G-Ly7ZlRoQWAbmEsAw7gQu9kj1ZKXee40mMvz2w_Ha9dfO2jeQqYlexJE9FuZt04Aw9KdGwN2GwPhZvX8ASwx-g04aNTzomQCvIStQVJs-p06zCBZQ==" },
  31: { id: 31, title: "adaventures.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHdC0cxNjfbl9jGzPlV6H27wBmRUnQszauTgTKoITtvMq27BJV54f818r79SSegzrgRRHJxXQc_eB-vgxhq-Nfw-ONHtFFFUE4I2RQt0qYwEDVFaiAUXrQElZAyQ3PN4iKaQ5etbRlYiO8=" },
  32: { id: 32, title: "sheffield.ac.uk", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFVIQB_TDBmhosCfVStHbcQXV-XjrW4XeWonmdgIFQGy8nWfYXbtMRqBMFEQbKxfQl4-NWSbZKwWx0AD5JlhEseR8Q3LFb1q_WuDeZH6V9h2mTK-Mj7xlwRGmjWj2eY0Ncl-KuJvKgZxQOJ9HqDUOT7-6q68E-aQWy7k1AL09U6D2fW1NC60jXiMGK0wtvkApZSjd4kV17xG96nED4JHdD00O8Z0V6ylskdLvaEdKdprHL0lhTvpEMEfiTndxYw2w==" },
  33: { id: 33, title: "mdpi.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQERF08TE5vpqqbofjTd2pDYlu9L7qtvkPWM2QqLk_4B1KN7eE7EnGXPr6y5Er9Bx659FonZaSjqClygeNhZ_SOTWqACc8VDHNJuJlwMSNIU2k7qDbHrNQsLftu9MVo=" },
  34: { id: 34, title: "qualityze.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHBMfz9pXoozXGLkmGuvX39smI_8PR9czDQo2BC73Nv06hXDsKogrSNo62SZVcWVCcowp1dbwsFSA-uwlS8ejaH8cIlehCAdAh--3BMM_KSgEEEgaXRzmzcK0PxqCfS8ijwS8Ea_TPEYRTf60zeAQ21PzxwULs4lxx5oa6IQmC7fFkGkkdj" },
  35: { id: 35, title: "scmglobe.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHBZ8lwRxr-5lN__DTO2CKdcnE8yVPsUlgMeO5s9QGDD3tkZrsi3b3w0jVUThpGIY6gsMQsyEqIu52cBOWOPOiH5x9MzTjcGV7JgMZ8wv1jQx5F86DpQ758WlHTcIBSMONk-X9RFa0nJaULFUD6DrSl6UjexhHnCoXZebSGby3tWuUD3rKDyaI=" },
  36: { id: 36, title: "xoriant.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEdoDDeT2dahG4_c3FjW_FZRlvhwU1azIXPKEUjsX5N5jZWefOirhPhXu2GKEcCVMB0cNlgj-mz9SP64mnz1wHLMAuplmbp-SJrmdeGWRTGtlbJ_FBYBUTAaGCgLJm_IHunJQ3tuVpyIeuiz0pTzRhwVVFLCbfPluFgtBFaT1_nkIQShM4ky5imyVIHcZgZu563" },
  37: { id: 37, title: "dmgmori.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFKuB0GJe25uPQmzLi8P4qeAoTXiSoQlhuZUEWWku5POA5bvH5RnHSKteYnk5_N5znOlv7QovKbUr0Yn-P83-eDgVOC0IkS0bpYyoa8vpAQbv7a94Iat3VqFhhGtjyqI-wHShiLTWJ1RfynSXhMCB_RrvuNBhdBo7a80gfaW8I_I10qybw=" },
  38: { id: 38, title: "dhl-freight-connections.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEMlz6K52l8dDQXhOH_SoduWPr-lV1Os0X9i6Iwo0y4w8Re3R8xwa5khzGbj3KoH2Qb9X9CfGQXQVBnrOPqY2FRSzJzF-kiddrfStjyyH8-fgocH_30Wv_0AbVUQnk0myvREZDU1xBGTr-MnaTRf0ieTHdj3qInuzMH2Y_UIOQFDjQa0CNIGiraZLFFYSyvuLrp24dvcALIE9QaSj9hs_GDMKou" },
  39: { id: 39, title: "zeal3dprinting.com.au", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQG-BLPIqA-u2Y4Z1mH-ex52h9k4ReBNuKC2WQekuCCimVyhPcHGSuy48ouO1gVke53JsBjBnP51_Hb-PfcyOgmpf_QQhTyz2AmxuDgQHyfXCX2YRSriQ79N62aoZLmYxwXQSyqDiRCgzCFfcBNWLER5xMFwtsxx03UDANxi9VOAP56azqvdATPZZ0kv73z5F3XtJZ24MXFAuszPFmlXQqXi4XcNUFyv" },
  40: { id: 40, title: "dinocajic.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGBjD8n3q5B9iNboptdgEGAYWL47O2stBB48zOWkdpBlkAZgWVdBO9MN_F5cfa4ix3xXbZcD5QTt1iocT8YS66KVhu8tqW7TetncDpEABA4c__jzjWM-KFDoYNmy-TqnxOdghPLAle2fKG-fcPBAzqtlhAIPLjEPTc8A5AWmORaT1m_zosQkhr4ZVBMV5H-v8ZjUKMe3paxarywY6Ol2NsEaQnTb_XEVgznx9I8" },
  41: { id: 41, title: "verytechnology.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGQcZfIpJbSvhhvG84951A_fFGOu4QrjAPPa2ECj275K0nCNaKM3v7rRo4SL5YNYjDKpJqEGkCZhQ9Fr1weRo6G43OmuC0X4yURZ5QyUhjoH-onCMMzlgE88OlI9rr2Ip2n7Sh4GRZOov7zx3tWmw6bhu8OMqvRftWxoyK2V2fK-oW-ca-S0VAJXt7sOJAn93Wvnp7KVo2FIfj7iwgR" },
  42: { id: 42, title: "mckinsey.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFNwmgx1rpEtgHCCqQXR8AFIvd3Wa6YFRJAoQnZ5w3qQ2uOuy-0dwbjmKypgV62yIxrf8E5eQU1p7_jFgwfgzxgxsnTBFYe5tQgCm4J6kbVb7tafco9w9kTBdNxHE69Zent6QTt_dLWBcr4WGyNPNGeTRcsrTh8x896zK0momFCM91Iu2FuYkn_CPj37Jmsp4u_5_ctux6jS7ubyZGzkkEwsd4TO-g5ZCNAswxmtuhMhOGX5lIHoVHJPsPoDa4XrA==" },
  43: { id: 43, title: "8thlight.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHAbFFAtPv3zSXaHze2W8hVOzU0PbWK_e71hqLbApII9ENEpqapoKtEzOKEoaT6O9o0X8baG5YnlmkeH476huhNijfIlRSEKWIB_6hAxq0-8poomJrO3grLCbsd57OX_QspO8T6SvtSju4uCOrYWfmi" },
  44: { id: 44, title: "reco.ai", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHB8nOSQaFopJIvYP8euAb_7VO7cCAf1Unf8dIbCIxgbpoW4Gt8xMQrZRVctEtviNyo4PfMK6mJECzqIccPv3EgdrYpXlhYS9RaQ4pPBUK7z_xc1I-k8SSNxYh8d3r1Qi1sdzNYEw==" },
  45: { id: 45, title: "vanta.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEDeyLX8VmWK8VRz5-V1KFAVnu1Di_T70d72mj-_ugehQYsFdYV_6ZlCdz_RQ1pku1ukv9rXtkKO91QcN7t6LLVDdIYVjL1Nx9u3UGTul6ELolYHfzJOoVd6KOLg_7Q" },
  46: { id: 46, title: "getmaxim.ai", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGbTSOdzHOgQ_ugBzT-3aFKb2okRkC_pUCJDQ0weXVGoX_NPgxdKLpM9I9jVH0OQwBZ1TE99psRH3Z-YyXSgpurhNJIDti_C448JS4n7u-6U1sYItoIJSk5Hs-rja2ro1ybH5FlPCkrirHY0qbGXCtGG1BZc-zSXVeamiTz" },
  47: { id: 47, title: "credo.ai", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHnaFsrGqi0T14J2Ab-jOKd-dPeKfWIF4lsXdMFMnTBfZAW-BQHlx9wTmG2JaA3niwISlSJ5IQl3XOewJ1wleJClndOPD8Q7oiL1e7PEN9Qv1PDujDeCS5uiaP9mKc_RUM1S1YvSt1iae_hU6R-AYT6wEgbpaHWi5TrFcxI_16GqnRkbLQ5XnobYZXl9T7w6WxFo0qtiFHnffYqHl8g" },
  48: { id: 48, title: "softwareimprovementgroup.com", url: "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFyvGx08sQ8B5bxxXO2XOfHCzmG522tgQMf4etr47eG-6qkYf_x8PQTw0gUmv9dNxqYoEiafY0mt3ahZJrS7pjzPc8AFYaW9HQB735S2JrzziOo13WYjuXpKrzj_0JyAzYKLk-WeiLFtqnAJqHkeoxH2ykBRApV-r69" },
};

/**
 * Get citation URLs by ID
 * @param ids - Array of citation ID numbers
 * @returns Array of Citation objects
 */
export function getCitations(ids: number[]): Citation[] {
  return ids
    .map((id) => citations[id])
    .filter((citation) => citation !== undefined);
}

/**
 * Get citation URLs by ID (for backwards compatibility)
 * @param ids - Array of citation ID numbers
 * @returns Array of URLs
 */
export function getCitationUrls(ids: number[]): string[] {
  return getCitations(ids).map((c) => c.url);
}

/**
 * Get a single citation by ID
 * @param id - Citation ID number
 * @returns Citation object or undefined
 */
export function getCitation(id: number): Citation | undefined {
  return citations[id];
}
