import {
  Binary,
  Brain,
  Cog,
  Factory,
  Flame,
  FlaskConical,
  Laptop,
  Leaf,
  Pickaxe,
  Recycle,
  Ruler,
  Scissors,
  ShoppingCart,
  Target,
  Trash2,
} from "lucide-react";

export const hardwareLifecycleFlow = {
  aiGeneratedNodes: [
    {
      id: "A",
      position: { x: 0, y: 0 },
      data: {
        label: "Extraction",
        sublabel: "Raw Materials",
        icon: <Pickaxe size={20} strokeWidth={2} />,
        color: "#991b1b",
      },
    },
    {
      id: "B",
      position: { x: 320, y: 0 },
      data: {
        label: "Manufacturing",
        sublabel: "Assembly & Testing",
        icon: <Factory size={20} strokeWidth={2} />,
        color: "#991b1b",
      },
    },
    {
      id: "C",
      position: { x: 640, y: 0 },
      data: {
        label: "Use",
        sublabel: "Active Deployment",
        icon: <Laptop size={20} strokeWidth={2} />,
        color: "#991b1b",
      },
    },
    {
      id: "D",
      position: { x: 960, y: 0 },
      data: {
        label: "Disposal",
        sublabel: "E-Waste & Recycling",
        icon: <Recycle size={20} strokeWidth={2} />,
        color: "#991b1b",
      },
    },
  ],
  aiGeneratedEdges: [
    {
      id: "eA-B",
      source: "A",
      target: "B",
      sourceHandle: "right-source",
      targetHandle: "left",
      type: "smoothstep",
      animated: true,
      style: {
        stroke: "#991b1b",
        strokeWidth: 2,
        opacity: 0.5,
      },
    },
    {
      id: "eB-C",
      source: "B",
      target: "C",
      sourceHandle: "right-source",
      targetHandle: "left",
      type: "smoothstep",
      animated: true,
      style: {
        stroke: "#991b1b",
        strokeWidth: 2,
        opacity: 0.5,
      },
    },
    {
      id: "eC-D",
      source: "C",
      target: "D",
      sourceHandle: "right-source",
      targetHandle: "left",
      type: "smoothstep",
      animated: true,
      style: {
        stroke: "#991b1b",
        strokeWidth: 2,
        opacity: 0.5,
      },
    },
  ],
};

export const redGreenFlow = {
  aiGeneratedNodes: [
    {
      id: "R1",
      position: { x: 0, y: 20 },
      data: {
        label: "Maximize Accuracy",
        sublabel: "Red AI",
        icon: <Target size={20} strokeWidth={2} />,
        color: "#991b1b",
      },
    },
    {
      id: "R2",
      position: { x: 300, y: 20 },
      data: {
        label: "Massive Models",
        sublabel: "Red AI",
        icon: <Brain size={20} strokeWidth={2} />,
        color: "#991b1b",
      },
    },
    {
      id: "R3",
      position: { x: 600, y: 20 },
      data: {
        label: "High Carbon Cost",
        sublabel: "Red AI",
        icon: <Flame size={20} strokeWidth={2} />,
        color: "#991b1b",
      },
    },
    {
      id: "G1",
      position: { x: 0, y: 180 },
      data: {
        label: "Efficiency Metric",
        sublabel: "Green AI",
        icon: <Ruler size={20} strokeWidth={2} />,
        color: "#2d6a2e",
      },
    },
    {
      id: "G2",
      position: { x: 300, y: 180 },
      data: {
        label: "Optimized Models",
        sublabel: "Green AI",
        icon: <Cog size={20} strokeWidth={2} />,
        color: "#2d6a2e",
      },
    },
    {
      id: "G3",
      position: { x: 600, y: 180 },
      data: {
        label: "Sustainable Scale",
        sublabel: "Green AI",
        icon: <Leaf size={20} strokeWidth={2} />,
        color: "#2d6a2e",
      },
    },
  ],
  aiGeneratedEdges: [
    {
      id: "eR1-R2",
      source: "R1",
      target: "R2",
      sourceHandle: "right-source",
      targetHandle: "left",
      type: "smoothstep",
      animated: true,
      style: { stroke: "#991b1b", strokeWidth: 2, opacity: 0.55 },
    },
    {
      id: "eR2-R3",
      source: "R2",
      target: "R3",
      sourceHandle: "right-source",
      targetHandle: "left",
      type: "smoothstep",
      animated: true,
      style: { stroke: "#991b1b", strokeWidth: 2, opacity: 0.55 },
    },
    {
      id: "eG1-G2",
      source: "G1",
      target: "G2",
      sourceHandle: "right-source",
      targetHandle: "left",
      type: "smoothstep",
      animated: true,
      style: { stroke: "#2d6a2e", strokeWidth: 2, opacity: 0.55 },
    },
    {
      id: "eG2-G3",
      source: "G2",
      target: "G3",
      sourceHandle: "right-source",
      targetHandle: "left",
      type: "smoothstep",
      animated: true,
      style: { stroke: "#2d6a2e", strokeWidth: 2, opacity: 0.55 },
    },
  ],
};

export const compressionFlow = {
  aiGeneratedNodes: [
    {
      id: "Input",
      position: { x: 280, y: 0 },
      data: {
        label: "Large Model",
        sublabel: "Teacher Model",
        icon: <Brain size={20} strokeWidth={2} />,
        color: "#991b1b",
      },
    },
    {
      id: "Q",
      position: { x: 0, y: 160 },
      data: {
        label: "Quantization",
        sublabel: "Lower Precision",
        icon: <Binary size={20} strokeWidth={2} />,
        color: "#1a1a1d",
      },
    },
    {
      id: "P",
      position: { x: 280, y: 160 },
      data: {
        label: "Pruning",
        sublabel: "Sparse Weights",
        icon: <Scissors size={20} strokeWidth={2} />,
        color: "#1a1a1d",
      },
    },
    {
      id: "D",
      position: { x: 560, y: 160 },
      data: {
        label: "Distillation",
        sublabel: "Student Training",
        icon: <FlaskConical size={20} strokeWidth={2} />,
        color: "#1a1a1d",
      },
    },
    {
      id: "Output",
      position: { x: 280, y: 320 },
      data: {
        label: "Efficient Model",
        sublabel: "Green Deployment",
        icon: <Leaf size={20} strokeWidth={2} />,
        color: "#2d6a2e",
      },
    },
  ],
  aiGeneratedEdges: [
    {
      id: "eInput-Q",
      source: "Input",
      target: "Q",
      sourceHandle: "bottom-source",
      targetHandle: "top",
      type: "smoothstep",
      animated: true,
      style: { stroke: "#991b1b", strokeWidth: 2, opacity: 0.55 },
    },
    {
      id: "eInput-P",
      source: "Input",
      target: "P",
      sourceHandle: "bottom-source",
      targetHandle: "top",
      type: "smoothstep",
      animated: true,
      style: { stroke: "#991b1b", strokeWidth: 2, opacity: 0.55 },
    },
    {
      id: "eInput-D",
      source: "Input",
      target: "D",
      sourceHandle: "bottom-source",
      targetHandle: "top",
      type: "smoothstep",
      animated: true,
      style: { stroke: "#991b1b", strokeWidth: 2, opacity: 0.55 },
    },
    {
      id: "eQ-Output",
      source: "Q",
      target: "Output",
      sourceHandle: "bottom-source",
      targetHandle: "left",
      type: "smoothstep",
      animated: true,
      style: { stroke: "#2d6a2e", strokeWidth: 2, opacity: 0.55 },
    },
    {
      id: "eP-Output",
      source: "P",
      target: "Output",
      sourceHandle: "bottom-source",
      targetHandle: "top",
      type: "smoothstep",
      animated: true,
      style: { stroke: "#2d6a2e", strokeWidth: 2, opacity: 0.55 },
    },
    {
      id: "eD-Output",
      source: "D",
      target: "Output",
      sourceHandle: "bottom-source",
      targetHandle: "right",
      type: "smoothstep",
      animated: true,
      style: { stroke: "#2d6a2e", strokeWidth: 2, opacity: 0.55 },
    },
  ],
};

export const circularEconomyFlow = {
  aiGeneratedNodes: [
    {
      id: "P",
      position: { x: 280, y: 0 },
      data: {
        label: "Production",
        sublabel: "Manufacturing",
        icon: <Factory size={20} strokeWidth={2} />,
        color: "#991b1b",
      },
    },
    {
      id: "C",
      position: { x: 560, y: 140 },
      data: {
        label: "Consumption",
        sublabel: "Usage Phase",
        icon: <ShoppingCart size={20} strokeWidth={2} />,
        color: "#991b1b",
      },
    },
    {
      id: "W",
      position: { x: 280, y: 280 },
      data: {
        label: "Waste",
        sublabel: "Discarded Materials",
        icon: <Trash2 size={20} strokeWidth={2} />,
        color: "#991b1b",
      },
    },
    {
      id: "R",
      position: { x: 0, y: 140 },
      data: {
        label: "Recycling",
        sublabel: "Recovery Streams",
        icon: <Recycle size={20} strokeWidth={2} />,
        color: "#2d6a2e",
      },
    },
  ],
  aiGeneratedEdges: [
    {
      id: "eP-C",
      source: "P",
      target: "C",
      sourceHandle: "right-source",
      targetHandle: "top",
      type: "smoothstep",
      animated: true,
      style: { stroke: "#991b1b", strokeWidth: 2, opacity: 0.55 },
    },
    {
      id: "eC-W",
      source: "C",
      target: "W",
      sourceHandle: "left-source",
      targetHandle: "right",
      type: "smoothstep",
      animated: true,
      style: { stroke: "#991b1b", strokeWidth: 2, opacity: 0.55 },
    },
    {
      id: "eW-R",
      source: "W",
      target: "R",
      sourceHandle: "left-source",
      targetHandle: "bottom",
      type: "smoothstep",
      animated: true,
      label: "AI Sorting",
      style: { stroke: "#2d6a2e", strokeWidth: 2, opacity: 0.6 },
    },
    {
      id: "eR-P",
      source: "R",
      target: "P",
      sourceHandle: "right-source",
      targetHandle: "left",
      type: "smoothstep",
      animated: true,
      label: "Materials",
      style: { stroke: "#2d6a2e", strokeWidth: 2, opacity: 0.6 },
    },
  ],
};
