#!/usr/bin/env node

/**
 * Extract Citations from deepResearch.md
 *
 * This script parses a deepResearch.md file and extracts the Sources section,
 * creating a structured TypeScript file with citation mappings.
 *
 * Usage: node extractCitations.js <path-to-deepResearch.md> <output-path>
 * Example: node extractCitations.js ./deepResearch.md ./deepResearchCitations.ts
 */

const fs = require("fs");
const path = require("path");

function extractCitations(filePath, outputPath) {
  // Read the deepResearch.md file
  if (!fs.existsSync(filePath)) {
    console.error(`Error: File not found: ${filePath}`);
    process.exit(1);
  }

  const content = fs.readFileSync(filePath, "utf-8");

  // Find the Sources section - look for "Sources:" text
  const sourcesIndex = content.indexOf("**Sources:**");

  if (sourcesIndex === -1) {
    console.error(
      "Error: No Sources section found in deepResearch.md\nExpected format: '**Sources:**'",
    );
    process.exit(1);
  }

  // Extract everything after **Sources:**
  const sourcesText = content.substring(sourcesIndex + "**Sources:**".length);

  // Extract citation entries: "1. [domain](url)"
  const citationRegex = /^(\d+)\.\s*\[([^\]]+)\]\((https?[^)]+)\)/gm;
  const citations = {};
  const citationsList = [];

  let match;
  while ((match = citationRegex.exec(sourcesText)) !== null) {
    const [, id, title, url] = match;
    const numId = parseInt(id, 10);
    citations[numId] = {
      id: numId,
      title,
      url,
    };
    citationsList.push({ id: numId, title, url });
  }

  if (citationsList.length === 0) {
    console.error(
      "Error: No citations found in Sources section. Expected format: '1. [title](url)'",
    );
    process.exit(1);
  }

  // Generate TypeScript file
  const tsContent = `/**
 * DeepResearch Citations - Auto-generated from deepResearch.md
 * 
 * This file contains the numbered citations extracted from the deepResearch.md Sources section.
 * Each citation includes the ID, title (domain), and URL.
 * 
 * Auto-generated by: scripts/extractCitations.js
 * DO NOT edit manually - regenerate by running: node scripts/extractCitations.js ./deepResearch.md ./deepResearchCitations.ts
 */

export interface Citation {
  id: number;
  title: string;
  url: string;
}

export const citations: Record<number, Citation> = {
${citationsList.map((c) => `  ${c.id}: { id: ${c.id}, title: "${c.title}", url: "${c.url}" },`).join("\n")}
};

/**
 * Get citation URLs by ID
 * @param ids - Array of citation ID numbers
 * @returns Array of Citation objects
 */
export function getCitations(ids: number[]): Citation[] {
  return ids
    .map((id) => citations[id])
    .filter((citation) => citation !== undefined);
}

/**
 * Get citation URLs by ID (for backwards compatibility)
 * @param ids - Array of citation ID numbers
 * @returns Array of URLs
 */
export function getCitationUrls(ids: number[]): string[] {
  return getCitations(ids).map((c) => c.url);
}

/**
 * Get a single citation by ID
 * @param id - Citation ID number
 * @returns Citation object or undefined
 */
export function getCitation(id: number): Citation | undefined {
  return citations[id];
}
`;

  // Write the output file
  fs.writeFileSync(outputPath, tsContent, "utf-8");
  console.log(
    `✓ Successfully extracted ${citationsList.length} citations to: ${outputPath}`,
  );
  console.log(`  Citation IDs: ${citationsList.map((c) => c.id).join(", ")}`);
}

// Get command line arguments
const args = process.argv.slice(2);

if (args.length < 2) {
  console.error(
    "Usage: node extractCitations.js <path-to-deepResearch.md> <output-path>",
  );
  console.error(
    "Example: node extractCitations.js ./deepResearch.md ./deepResearchCitations.ts",
  );
  process.exit(1);
}

const [deepResearchPath, outputPath] = args;
extractCitations(deepResearchPath, outputPath);
